[versions]
androidtools-common = "31.8.1"

kotlinx-bcv = "0.17.0"

[libraries]
androidtools-common = { module = "com.android.tools:common", version.ref = "androidtools-common" }

[plugins]

kotlinx-binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-bcv" }
